version: '3'
services:
  asana_db:
    image: postgres
    ports:
      - "5433:5432"
    env_file: ./dockerfiles/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  asana_project:
    build: ./
    env_file: ./dockerfiles/.env
    working_dir: /var/www/asana
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/var/www/asana
    links:
      - asana_db
    ports:
      - "8000:8000"

volumes:
  postgres_data: